//Projects Data
export const FETCHING_PROJECT_DATA = 'FETCHING_PROJECT_DATA';
export const FETCHED_PROJECTS_DATA = 'FETCHED_PROJECTS_DATA';
export const FETCHING_STAFF_DATA = 'FETCHING_STAFF_DATA';
export const FETCHED_STAFF_DATA = 'FETCHED_STAFF_DATA';
export const FETCHING_AWARDS_DATA = 'FETCHING_AWARDS_DATA';
export const FETCHED_AWARDS_DATA = 'FETCHED_AWARDS_DATA';
export const ERROR = 'ERROR';
export const FETCHED_PROJECT_DATA = "FETCHED_PROJECT_DATA"

//Language
export const LOCALE_SET = 'LOCALE_SET';

