//Projects Data
export const FETCHING_PROJECTS_DATA = 'FETCHING_PROJECTS_DATA';
export const FETCHED_PROJECTS_DATA = 'FETCHED_PROJECTS_DATA';
export const ERROR = 'ERROR';
export const FETCHED_PROJECT_DATA = "FETCHED_PROJECT_DATA"

//Language
export const LOCALE_SET = 'LOCALE_SET';

